### PR TITLE
add Oracle Cloud Infrastructure Container Engine for Kubernetes provider

### PR DESCRIPTION
**Pull request by hhuiliu**

### CODE REVIEW

**Comment by jstrachan** [comment]
@hhuiliu btw I've already added `oracle` as a provider https://github.com/jenkins-x/cloud-environments/tree/master/env-oracle along with adding it into the jx CLI - wonder if we could stick with that?

https://github.com/jenkins-x/jx/blob/99f24344a2de59c840d9b7799dd2b9500fc79b00/pkg/jx/cmd/create_cluster.go#L34-L43

**Comment by hhuiliu** [comment]
Hi @jstrachan , thanks a lot for the quick feedback.  Yeah, we noticed the related changes for oracle you have made both in cloud-environment and jx project. As Oracle would like to release the cloud provider with name "oce" and we have prepared the jx CLI code which is also named "oce". We will submit the pull-request once the rest open source process is done for jx CLI.

**Comment by jstrachan** [comment]
ok fine with me - lets remove the `oracle` provider from jx to follow suit

**Comment by hhuiliu** [comment]
Thanks a lot @jstrachan.

**Pull request merged**
