### PR TITLE
Add IBM Cloud Private environment

### PR DESCRIPTION
**Pull request by a-roberts**
Goes with https://github.com/jenkins-x/jx/pull/2073 which includes more details and an example of the output.

### CODE REVIEW

**Comment by ccojocar** [comment]
@a-roberts Please could you rebase and fix the conflicts tin the Makefile? Thanks

**Comment by a-roberts** [comment]
Rebased and addressed any conflicts, anything I need to do next?

**Comment by a-roberts** [comment]
Job failed but can't see why, gotta log in

**Pull request merged**
